### ISSUE TITLE
鍵の管理ってどうしたら？

### ISSUE THREAD

**Issue by yosei** [codeformiyazaki/m-tsunami-ios#13]
push notificationに必要な鍵や、管理画面のパスワード設定をどこに置こうか迷い中です。code4miyazakiのプライベートなリポジトリがあれば良いのかな。

**Comment by koogawa** [comment]
私が所属している会社の場合は、fastlane match というサービスを使ってプライベートなリポジトリに証明書や鍵などを保管しております！

fastlane match を使用して iOS の証明書管理を行う - Qiita https://qiita.com/kotarella1110/items/840af2cf80aaea1fb035

**Comment by yosei** [comment]
なるほど！勉強してみます！> match  出だしの一文に深く同意 (^^;

> iOS 開発において「証明書」という単語を聞くだけでアレルギー反応を起こす人も少なくないかもしれません。

**Comment by yosei** [comment]
とりあえず、会社のプライベートリポジトリにheroku関連のキーを収めてまあ動いてるので、一旦クローズします…！ fastlaneの勉強は改めて個人の課題としてやってみます。
