### ISSUE TITLE
[ios]初回起動直後に現在地を表示できない

### ISSUE THREAD

**Issue by yosei** [codeformiyazaki/m-tsunami-ios#21]
![IMG_6663](https://user-images.githubusercontent.com/4746659/64219793-e5de9f80-cf01-11e9-9b19-60e7cf17e78a.PNG)
![IMG_6664](https://user-images.githubusercontent.com/4746659/64219794-e6773600-cf01-11e9-8890-69df78f99c54.PNG)

現在位置取得の許可を求めるダイアログが出るため、今までのタイミングでは現在地にジャンプできない模様…。ダイアログが消えた直後（許可を取得した直後）に更新できないか？

**Comment by koogawa** [comment]
許可を取得したタイミングで

`    func locationManager(_ manager: CLLocationManager, didChangeAuthorization status: CLAuthorizationStatus) {`

が呼ばれるので、そこで現在地にジャンプするようにしてみます。

**Comment by yosei** [comment]
めちゃくちゃ対応早い…！ありがとうございます！
