### ISSUE TITLE
iOS13の地図に施設名が出ない？

### ISSUE THREAD

**Issue by yosei** [codeformiyazaki/m-tsunami-ios#25]
シミュレータ上だけの問題かも？実機が手元にある段階で再度検証。

**Comment by koogawa** [comment]
iOS 13 実機で確認しました。

<img src=https://user-images.githubusercontent.com/893643/66145671-49b1d080-e646-11e9-9abd-ad360dbb1175.png  width=50%>

この図でいうと「宮崎グリーンホテル」みたいなのが施設名でしょうか！
表示されているように見えます

**Comment by yosei** [comment]
@koogawa 確認ありがとうございます！こちらも実機では問題なかったので、シミュレータの動きかもしれません。新しいピン（避難所の位置）を追加したバージョン1.1.1をリリースしました！（勉強会の中でやってしまったので、プルリクとか飛ばしてしまってすみません。
