### ISSUE TITLE
[ios]宮崎市の防災情報を載せる？

### ISSUE THREAD

**Issue by yosei** [codeformiyazaki/m-tsunami-ios#35]
現在の気象庁のデータの代わりに？
給水所などの情報が市のサイトに載るのでリンクを貼る？(RSSは未対応)

**Comment by yosei** [comment]
GoogleのマイマップへのリンクをAlertsの代わりに載せる？

**Comment by yosei** [comment]
この課題は、 #102 で市役所のウェブサイトにリンクを作ったので一旦クローズでどうでしょうか？

**Comment by koogawa** [comment]
Agreeです！
