### ISSUE TITLE
[ios]「現在地」「アイコンの説明」をアイコンにしてはどうか？

### ISSUE THREAD

**Issue by yosei** [codeformiyazaki/m-tsunami-ios#44]
在住の外国人でも想像で使えるかな、と。

**Comment by yosei** [comment]
near me: <img src="https://github.com/codeformiyazaki/m-tsunami-ios/blob/issue/34/iosapp/06-earthquake/Assets.xcassets/near-me.imageset/baseline_near_me_black_18dp.png?raw=true" />

layers: <img src="https://github.com/codeformiyazaki/m-tsunami-ios/blob/issue/34/iosapp/06-earthquake/Assets.xcassets/layer.imageset/baseline_layers_black_18dp.png?raw=true" />

**Comment by koogawa** [comment]
たしかに！！

**Comment by koogawa** [comment]
close #46
