### ISSUE TITLE
マッピングするためのI/Fフォーマット決め

### ISSUE THREAD

**Issue by MTROOT3894** [codeformiyazaki/m-tsunami-ios#7]
緯度、経度、高度、付加情報

**Comment by yosei** [comment]
GitHubだとCSVも見やすく表示してくれるんですね…！（こうなるとCSVが便利かもですね
住所から自動算定したものなので、座標が違ってる建物がありそうです。間違いはpull requestでご指摘頂ければ順次取り込むという運用はどうでしょうか？（修正の都度アプリのリリースが必要にはなるんですが、そんなに多数は来ないだろうという想定です）

https://github.com/code4miyazaki/m-tsunami-ios/blob/master/iosapp/06-earthquake/buildings_locations.csv

**Comment by kenzkenz** [comment]
あら。すでに緯度経度はついていたのですね。付いていないtsvから緯度経度を取得してgeojsonを作ってしまいました。

**Comment by yosei** [comment]
プルリクでのご指摘通り、住所->経度緯度の自動変換は100%正確ではなさそうなので、個別に確認・修正が必要かと思います。今はCSVを読んでますが、JSONの方が後々便利かも？ですね。

**Comment by yosei** [comment]
geojsonがGitHubと相性良くて便利なので、jsonで行くことにしました！（といってもSwiftで扱いづらいので中でcsv変換してますが(^^;
