### ISSUE TITLE
[ios]スクリーンロック中でもpush通知可能？

### ISSUE THREAD

**Issue by yosei** [codeformiyazaki/m-tsunami-ios#74]
音を設定したら良いのかな？

**Comment by koogawa** [comment]
push 通知可能です！

sample:

```
{
“aps”: {
  “alert”:“Testing.. (0)“,
  “badge”:1,
  “sound”:“default”,
  }
}
```

**Comment by yosei** [comment]
できました！よい音源が手に入ったらカスタムサウンドにも挑戦してみたいです。

公式ドキュメント中で言われている "the sound dictionary" って何のことでしょう…？

> Specify the string "default" to play the system sound. Use this key for regular notifications. For critical alerts, use the sound dictionary instead.

https://developer.apple.com/documentation/usernotifications/setting_up_a_remote_notification_server/generating_a_remote_notification

**Comment by yosei** [comment]
終わってますね。（閉じ忘れ）
