### ISSUE TITLE
[ios]マイページに写真が出ない？？

### ISSUE THREAD

**Issue by yosei** [codeformiyazaki/m-tsunami-ios#79]
2枚目に撮影した画像が地図上には掲載されているのにマイページに登場してこない？？

![IMG_0352](https://user-images.githubusercontent.com/4746659/71961912-bdfaa200-323b-11ea-9cf7-51b188542db3.PNG)

![IMG_0353](https://user-images.githubusercontent.com/4746659/71961913-bdfaa200-323b-11ea-800d-9365c50bc9eb.PNG)

**Comment by yosei** [comment]
アプリを再起動したら出てきました！

**Comment by koogawa** [comment]
常に最新の投稿が出るようにした方が良いかもですね！
